/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Headphones.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Headphones.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Box002.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Foam.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Box004.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Foam001.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Box007.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Box008.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['01___Default']} />
    </group>
  )
}

useGLTF.preload('/Headphones.glb')
